#!/bin/sh

#####################################
###       Autostart Section       ###
#####################################
sxhkd &
picom &
sh $HOME/.config/polybar/launch.sh &
nitrogen --restore &
xscreensaver -no-splash &

#####################################
###        Monitor Section        ###
#####################################
bspc monitor -d        
 

#####################################
###        BSPWM Config           ###
#####################################
bspc config border_width		2
bspc config window_gap          	10
bspc config top_padding			20
bspc config bottom_padding		5
bspc config left_padding		5
bspc config right_padding		5
bspc config split_ratio			0.50
bspc config single_monocle		false
bspc config focus_follows_pointer	true
bspc config borderless_monocle		true
bspc config gapless_monocle		true


######################################
###         BSPWM Colors           ###
######################################
bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color	"#304258"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color		"#8e1919"


###########################################
###         BSPWM Rules			###
###########################################
#bspc rule -a Alacritty desktop='^1' state=floating follow=on
#bspc rule -a Firefox desktop='^2' state=floating follow=on
#bspc rule -a pcmanfm desktop='^5' follow=on
